### PR TITLE
this has the login and signup pages with css [ Delivers #160453500 ]

### PR DESCRIPTION
**Pull request by habatkasa**
@tomuhenry 
@king-benx
@armstrongsouljah

### CODE REVIEW

**Comment by mwinel** [comment]
Please attach the relevant user story ID in your PR message.

**Comment by habatkasa** [comment]
do you mean the pivotal tracker story id?
@mwinel

**Comment by mwinel** [comment]
@habatkasa yes, that way I am able to relate if the story matches your code implementation.

**Comment by habatkasa** [comment]
@tomuhenry @medihamad @henrykamoga
please review my code

**Pull request merged**
